Fix tautological pointer comparison issues in ../xplat/privacy_infra/anon_cred/v3/lib/tests/kdf_test.cpp (#18)
Summary:
Pull Request resolved: https://github.com/facebookresearch/acs/pull/18

Required for LLVM-17.

Fixes
```
      8 xplat/privacy_infra/anon_cred/v3/lib/tests/kdf_test.cpp:175:27: error: comparison of array 'pk_proof' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
```

Reviewed By: palmje

Differential Revision: D56207657

fbshipit-source-id: 5c6a117f86c27819d1a10ec86e941e291dba3647