Fix tautological pointer comparison issues in ../xplat/privacy_infra/anon_cred/v3/lib/tests/kdf_test.cpp
Summary:
Required for LLVM-17.

Fixes
```
      8 xplat/privacy_infra/anon_cred/v3/lib/tests/kdf_test.cpp:175:27: error: comparison of array 'pk_proof' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
```

Reviewed By: palmje

Differential Revision: D56207657